apiVersion: v1
kind: Service
metadata:
  labels:
    app: placement
  name: placement
spec:
  ports:
    - name: "50006"
      port: 50006
      targetPort: 50006
  selector:
    app: placement
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: placement
  name: placement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: placement
  template:
    metadata:
      labels:
        app: placement
    spec:
      containers:
        - name: placement
          image: daprio/dapr
          args:
            - ./placement
            - -port
            - "50006"
          ports:
            - containerPort: 50006
              protocol: TCP
          imagePullPolicy: Never
      restartPolicy: Always
